baseURL = "https://sxy91.com/"
languageCode = "zh"
title = "宋洋葱的博客"
theme = "wehuth"
paginate = 10

#pygmentsCodefences = true # 代码高亮
hasCJKLanguage = true
watch = true

#uglyURLs = true # 使用html后缀


[blackfriday]
  extensions = ["noEmptyLineBeforeBlock"]

[menu]
  [[menu.main]]
    name = "生活"
    url = "/categories/life"
    weight = 1

  [[menu.main]]
    name = "技术"
    url = "/categories/code"
    weight = 3

  [[menu.main]]
    name = "读书"
    url = "/categories/read"
    weight = 5

  [[menu.main]]
    name = "工具"
    url = "/categories/tools"
    weight = 7

# Add your own params here
[params]
  home_path = "/categories/life"
  author = "宋洋葱"
  #aboutme = "javascript:;"
  aboutme = "https://github.com/smile365"
  subtitle = "若你欲哭无泪，我送你一颗洋葱啊"
  description = "研究互联网产品和技术，提供原创中文精品教程" # site description
  keywords = "javascript,html,jquery,git,python,java,css,linux,bitcoin,教程,软件,编程,开发,运维,云计算,网络,互联网,比特币,数字货币,博客,赚钱" # site keywords

  google_verification = ""
  bing_verification = ""
  yandex_verification = ""
  pinterest_verification = ""
  baidu_verification = ""
    

  license= 'Released under <a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

  # Choose your social networks
  github = "https://github.com/smile365"
  wechat= "https://github.com/smile365" 
  zhihu = "https://www.zhihu.com/people/sxy91"
 